### ISSUE TITLE
Bug: Incompatible with Wilder Wild

### ISSUE THREAD

**Issue by Omni-MC** [TalonFox/EnhancedWeather#20] opened 2023-05-23 20:03 UTC
**Describe the bug**
Game crashes on startup with Wilder Wild installed.

**To reproduce**
Install Wilder Wild alongside Enhanced Weather and launch the game.

**Information**
 - Minecraft Version: 1.19.4
 - Fabric/Quilt Loader Version: 0.14.19
 - Fabric API Version: 0.81.1+1.19.4
 - EnhancedWeather Version: 1.0-Beta5.2
 - Loaded mods: A lot, but I'm certain only these two are of concern.

**Additional context**
I suspected it was Wilder Wild as the log shows an error with FrozenLib, which is used by Wilder Wild

Log - https://mclo.gs/0P5sm0V

**Comment by TalonFox** [comment] 2023-05-23 21:17
Hi @Omni-MC. I can confirm that FrozenLib is causing issues with Wilder Wild. However, fixing this issue is a bit difficult. You see both FrozenLib and Enhanced Weather need to override the default behavior of Vanilla Minecraft's lightning. However, only one mod is actually allowed to do this. Lightning wouldn't be able to spawn properly otherwise, and since both try to override it, it crashes. It is possible to fix this by making Enhanced Weather do its own lightning spawning instead of overriding the vanilla game's lightning spawning, however this is easier said than done. I'll keep this issue open, but just know that this will probably not get fixed for a while.

**Comment by TalonFox** [comment] 2023-07-28 20:13
Seems like FrozenLib doesn't conflict with Enhanced Weather anymore so I'm going to close this

**Closed by TalonFox** 2023-07-28 20:13 UTC
Labels: Bug, Confirmed Bug
